services:
  - type: web
    name: screenie
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python server.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: DATA_DIR
        value: /data
      - key: UPLOAD_FOLDER
        value: /data/uploads
      - key: DB_FILE
        value: /data/users.db

  - type: web
    name: adminer
    env: docker
    dockerfilePath: ./Dockerfile.adminer
    envVars:
      - key: ADMINER_DESIGN
        value: dracula
    plan: free