services:
  - type: web
    name: screenie
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: |
      echo -e "$ADMIN_USERNAME\n$ADMIN_PASSWORD\n$ADMIN_PASSWORD\n$ADMIN_EMAIL" | python create_admin.py
      gunicorn --bind 0.0.0.0:$PORT server:app
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_ORIGINS
        value: https://${RENDER_EXTERNAL_URL}
      - key: DATA_DIR
        value: /opt/render/project/src/data
      - key: PORT
        value: 10000
      - key: ADMIN_USERNAME
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
      - key: ADMIN_EMAIL
        sync: false 